spring:
  application:
    name: authentication

  # R2DBC setting
  r2dbc:
    url: r2dbc:mariadb://stg-yswa-kr-practice-db-master.mariadb.database.azure.com:3306/S10P22D204
    username: S10P22D204@stg-yswa-kr-practice-db-master.mariadb.database.azure.com
    password: rILtGmi1Wl
    properties:
      ssl: true
      serverTimezone: UTC
      useUnicode: true
      characterEncoding: utf8

  # Redis setting
  data:
    redis:
      port: 6379
      host: localhost
      url: redis://127.0.0.1:6379
      password: fastand6

  # jwt setting
  jwt:
    secret:
      access: ZmFzdC1hY2Nlc3MtZmFzdHJhdmVs
      refresh: ZmFzdC1yZWZyZXNoLWZhc3RyYXZlbA==

  # Kakao, google oauth
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: f7d9ac8edb4a0ef2b5319e2dbc8a03ce
            client-secret: mxNkQgScurfotd6DGrF84b3kRwGnPHZL
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            redirect-uri: http://localhost:5173
            scope:
              - profile_nickname
              - profile_image
              - account_email
          google:
            client-id: 342468503847-8218eafadnrh7kbkqdun2s6bhnk1aktr.apps.googleusercontent.com
            client-secret: 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
            scope:
              - openid
              - profile
              - email
            redirect-uri: http://localhost:5173
            client-authentication-method: basic
            authorization-grant-type: authorization_code
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub